### ISSUE TITLE
Inline/Embedded images are not being obtained as embedded images

### ISSUE THREAD

**Issue by prasunsultania** [bbottema/outlook-message-parser#1]
It works for the file provided in test but, does not works for the files i tried to test with
```
OutlookMessage outlookMessage = new OutlookMessageParser().parseMsg(new File("example.msg")); 
System.out.println(outlookMessage.fetchCIDMap().keySet().size()); // this is zero
System.out.println(outlookMessage.fetchTrueAttachments().size()); // this is 1
```
expecting CIDMap keyset size to 1 as the file has inline image

Sample email to reproduce the issue: https://ufile.io/1yztx (link is valid for 30 days only)

PLMK if you are able to reproduce it or if you need any other information.

**Comment by prasunsultania** [comment]
https://ufile.io/1yztx (link is valid for 30 days only)

**Comment by bbottema** [comment]
No code provided whatsoever, nothing to go on.

**Comment by prasunsultania** [comment]
`OutlookMessage outlookMessage = new OutlookMessageParser().parseMsg(new File("example.msg")); 
System.out.println(outlookMessage.fetchCIDMap().keySet().size()); // this is zero
System.out.println(outlookMessage.fetchTrueAttachments().size()); // this is 1
`

expecting CIDMap keyset size to 1 as the file has inline image

**Comment by prasunsultania** [comment]
PLMK if you are able to reproduce it or if you need any other information.

**Comment by bbottema** [comment]
@prasunsultania, can put up a link again, please?

**Comment by bbottema** [comment]
Closing as I don't have anything to go on and I'm not getting any further reaction resulting in a dead-end. I'm happy to reopen when I get more info.
