### ISSUE TITLE
HTML_START_TAGS contain extra space

### ISSUE THREAD

**Issue by fadeyev** [bbottema/outlook-message-parser#13]
SimpleRTF2HTMLConverter.HTML_START_TAGS are:
`private static final String[] HTML_START_TAGS = { "<html ", "<Html ", "<HTML " };`
and should be
`private static final String[] HTML_START_TAGS = { "<html", "<Html", "<HTML" };`

Because of this `fetchHtmlSection()` method add extra `<html>` tags for some emails which have simple opening html tag without any attributes

**Comment by bbottema** [comment]
Released v1.3.0
