### ISSUE TITLE
NPE on ClientSubmitTime when original message has not been sent yet

### ISSUE THREAD

**Issue by bbottema** [bbottema/outlook-message-parser#25]
Copied from https://github.com/bbottema/simple-java-mail/issues/243

> While investigating [bbottema/outlook-message-parser#23](https://github.com/bbottema/outlook-message-parser/issues/23) we found an issue with the OutlookMessage.getClientSubmitTime() method.
> 
> ```
> java.lang.NullPointerException
> 	at org.simplejavamail.outlookmessageparser.model.OutlookMessage.getClientSubmitTime(OutlookMessage.java:849)
> 	at org.simplejavamail.internal.outlooksupport.converter.OutlookEmailConverter.buildEmailFromOutlookMessage(OutlookEmailConverter.java:73)
> 	at org.simplejavamail.internal.outlooksupport.converter.OutlookEmailConverter.outlookMsgToEmailBuilder(OutlookEmailConverter.java:60)
> 	at org.simplejavamail.converter.EmailConverter.outlookMsgToEmailBuilder(EmailConverter.java:226)
> 	at org.simplejavamail.converter.EmailConverter.outlookMsgToEmail(EmailConverter.java:209)
> 	at org.simplejavamail.converter.EmailConverter.outlookMsgToEmail(EmailConverter.java:201)
> ```
> 
> The issue is present with the following test emails from the outlook-message-parser.
> 
> * tst_unicode.msg
> * unsent draft.msg
> * chinese message.msg
> * forward with attachments and embedded images.msg
> * the nested mail from 'nested simple mail.msg'

**Comment by bbottema** [comment]
[Released](https://app.circleci.com/jobs/github/bbottema/outlook-message-parser/50/parallel-runs/0/steps/0-105) in 1.7.1

**Comment by Faelean** [comment]
Seems like this created another issue:
This is from the tst_unicode.msg
```
java.lang.IllegalArgumentException: Implicit NotNull argument 1 of org/simplejavamail/email/internal/EmailPopulatingBuilderImpl.to must not be null
	at org.simplejavamail.email.internal.EmailPopulatingBuilderImpl.to(EmailPopulatingBuilderImpl.java)
	at org.simplejavamail.internal.outlooksupport.converter.OutlookEmailConverter.copyReceiversFromOutlookMessage(OutlookEmailConverter.java:97)
	at org.simplejavamail.internal.outlooksupport.converter.OutlookEmailConverter.buildEmailFromOutlookMessage(OutlookEmailConverter.java:77)
	at org.simplejavamail.internal.outlooksupport.converter.OutlookEmailConverter.outlookMsgToEmailBuilder(OutlookEmailConverter.java:60)
	at org.simplejavamail.converter.EmailConverter.outlookMsgToEmailBuilder(EmailConverter.java:226)
	at org.simplejavamail.converter.EmailConverter.outlookMsgToEmail(EmailConverter.java:209)
	at org.simplejavamail.converter.EmailConverter.outlookMsgToEmail(EmailConverter.java:201)
```

Second thing, I don't know if this might be a seperate issue:
Using the unsent draft.msg, the sender looks like this:

![image](https://user-images.githubusercontent.com/7944797/73073452-a9fba500-3eb7-11ea-8483-f4c2161ef389.png)

**Comment by bbottema** [comment]
> Seems like this created another issue:
> This is from the tst_unicode.msg

How do I reproduce this?

> Second thing, I don't know if this might be a seperate issue:

I'll have a look, thanks for the heads up.

**Comment by Faelean** [comment]
> > Seems like this created another issue:
> > This is from the tst_unicode.msg
> 
> How do I reproduce this, @Faelean?

I haven't change anything in my code, the two mails creating issues are the same as before. I haven't seen this issue because of the NullPointer.

**Comment by bbottema** [comment]
The first issue you reported is from Simple Java Mail, I don't know how you used the builder to get this error.

**Comment by Faelean** [comment]
Sorry I missunderstood, I commented here because you 'moved' the issue in Simple Java Mail here, the original call is EmailConverter.outlookMsgToEmail(stream) from Simple Java Mail.

**Comment by bbottema** [comment]
As for the `IllegalArgumentException`, please refer to https://github.com/bbottema/outlook-message-parser/issues/26.

**Comment by bbottema** [comment]
As for the other issue, I suspect this is an Outlook version problem where the properties work differently. This is an email that doersn't have a sent-address (yet), but the property for it is still encoded with a garbage value.

**Comment by bbottema** [comment]
@Faelean as for garbage sender issue, please refer to https://github.com/bbottema/outlook-message-parser/issues/27 (fix [released](https://app.circleci.com/jobs/github/bbottema/outlook-message-parser/57/parallel-runs/0/steps/0-105) in 1.7.3).

**Comment by bbottema** [comment]
@Faelean, Simple Java Mail now uses 1.7.3 in release 6.0.1
