### ISSUE TITLE
Chinese .msg is garbled when converted (missing UTF-8 support)

### ISSUE THREAD

**Issue by whaozl** [bbottema/outlook-message-parser#3]
```
o???á?<span lang=EN-US>   <o:p></o:p></span>  </span>  </span>    </p></td>  <span style='mso-bookmark:_MailAutoSig'>  </span>  <td width=142 nowrap style='width:106.3pt;border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;height:14.25pt'>  <p class=MsoNormal align=left style='text-align:left'>   <span style='mso-bookmark:_MailAutoSig'>  <span style='font-size:11.0pt;line-height:110%;color:black'>  è?ìì<span lang=EN-US>   <o:p></o:p></span>  </span>  </span>    </p></td>  <span style='mso-bookmark:_MailAutoSig'>  </span>  </tr></table>  <p class=MsoNormal style='line-height:normal;mso-pagination:none'>  <span style='mso-bookmark:_MailAutoSig'>  <span lang=EN-US style='mso-bidi-font-size:10.5pt;font-family:"?￠èí??oú",sans-serif;mso-no-proof:yes'>    <o:p>  </o:p></span>  </span>  </p><p class=MsoNormal style='line-height:normal;mso-pagination:none'>  <span style='mso-bookmark:_MailAutoSig'>  <span lang=EN-US style='mso-bidi-font-size:10.5pt;font-family:"?￠èí??oú",sans-serif;mso-no-proof:yes'>    <o:p>  </o:p></span>  </span>  </p><p class=MsoNormal style='line-height:normal;mso-pagination:none'>  <span style='mso-bookmark:_MailAutoSig'>  <span lang=EN-US style='mso-bidi-font-size:10.5pt;font-family:"?￠èí??oú",sans-serif;mso-no-proof:yes'>    Best Regards<o:p></o:p></span>  </span>  </p><p class=MsoNormal style='line-height:normal;mso-pagination:none'>  <span style='mso-bookmark:_MailAutoSig'>  <span lang=EN-US style='mso-bidi-font-size:10.5pt;font-family:"?￠èí??oú",sans-serif;mso-no-proof:yes'>
```
chinese msg is garbled, this can not handler chinese msg of outlook.

I want to convert msg to html.

**Comment by whaozl** [comment]
yeah, I have this msg, and As long as Chinese is garbled. So You can write a Chinese reference email. I offer one.  link：https://pan.baidu.com/s/1DDb6a7XggbtlB9IpnzPQQA   password：i3ta

**Comment by bbottema** [comment]
In fact the HTML content is only 56 bytes, so actually the source .msg is messed up. This library is trying to use it nonetheless, while Outlook ignores it and uses the RTF instead.

**Comment by bbottema** [comment]
@whaozl, how did you get that HTML output from your first post? Can you show me the code you used?

**Comment by whaozl** [comment]
```java
public class Demo04_outlook_message_parser {


	private static OutlookMessage parseMsgFile(String msgPath)
			throws IOException {
		InputStream resourceAsStream = OutlookMessageParser.class.getClassLoader().getResourceAsStream(msgPath);
		return new OutlookMessageParser().parseMsg(resourceAsStream);
	}


    public static void main(String[] args) {
        String path="D:\\Anjos\\01_project\\005_201808OverseaMail\\test\\example.msg";
        try {
            //OutlookMessage msg = parseMsgFile(path);
            InputStream in = new FileInputStream(path);
            OutlookMessage msg=new OutlookMessageParser().parseMsg(in);
            System.out.println(path);
        } catch (IOException e) {
            e.printStackTrace();
        }


    }

}

```
I am garbled through outlook-message-parser.

But this is normal by using [MsgViewer](https://github.com/lolo101/MsgViewer).

**I know it uses msgparser in the MsgViewer. Although it turned Chinese characters into GBKcode, I had to convert GBK encoding to UTF8.**

**However, msgparser and outlook-message-parser is mostly same.But  I am garbled alone in msgparser or outlook-message-parser.**

I do not know how it happened.

I am studying Chinese natural language processing and now need to handler outlook msg. I need to convert msg to html. Because I want to extract the entire table separately, it belongs to a complete semantic content. text can't do it.

**I am very grateful for your help, thank you very much.**

![0](https://user-images.githubusercontent.com/6327360/44306133-fb4a5f80-a3ba-11e8-95d2-1bdc8a374b40.png)

![1](https://user-images.githubusercontent.com/6327360/44306135-ff767d00-a3ba-11e8-87ae-7f4a1a267a72.png)

**Comment by bbottema** [comment]
Ok, so first thing: that .msg _has_ a native HTML body, but it is corrupted. The method you used (`getConvertedBodyHTML()`) is actually the RTF body converted to HTML. The RTF body is encoded properly showing chinese characters, but the converted HTML is not encoded properly, giving you the garbled text.

I can't fix the native HTML body (that's a problem in the .msg itself), but I can fix the `getConvertedBodyHTML`. I will work on it.

**Comment by whaozl** [comment]
yeah, the native html is not trusted. generally from RTF to HTML. As I know, MsgViewer and Aspose is normal, although they did not display Chinese characters normally.

Best Regards. Thank you for your help.

**Comment by bbottema** [comment]
I have found the problem and almost have a fix ready.

**Comment by bbottema** [comment]
That was quite an adventure. I included RTF -> HTML support from another library long time ago, but now I had to dive into the RTF spec and double byte encoding technology 😐

I ran into more problems, as RTF is actually parsed using the provided charset (in your .msg chinese, cp936) for visible text, but windows charset (cp1250) for control characters. Since the old library was implemented with regular expressions, this posed quite a challange.

I managed to solve it with some hacking work, but in the future I would like to switch to a token-based lexer/parser.

Released to maven version 1.1.17. Please verify the solution.

**Comment by bbottema** [comment]
That was quite an adventure.

I had included the RTF -> HTML support from another library loong time ago, but now I had to dive into the RTF spec and double byte encoding technology 😐

I ran into more problems, as RTF should actually be parsed using the provided charset (in your .msg chinese, cp936) for visible text, but windows charset (cp1250) for control characters. Since the old library was implemented with regular expressions, this posed quite a challange.

I managed to solve everything with some hacking work, but in the future I would like to switch to a token-based lexer/parser.

Released to maven version 1.1.17. Please verify the solution.

**Comment by whaozl** [comment]
yeah, Thank you so much for you help. I had test the solution, it is successful. you are very good.

**Comment by bbottema** [comment]
Thank you for the (detailed) bug report, @whaozl!
