### ISSUE TITLE
Parse error when trying to fetch true attachments

### ISSUE THREAD

**Issue by KacperFKorban** [bbottema/outlook-message-parser#31]
Parsing msg with attachment named `Attachment[1.pdf` and trying `fetchTrueAttachments()` throws an exception, because `cid:['\"]Attachment[1.pdf['\"]` is not a valid regex. (the square bracket isn't closed)

I created a PR with a fix for it #30.

**Comment by bbottema** [comment]
Apologies that it took so long for me to look at your problem and change. I've release your fix in 1.7.5, thank you for the effort, much appreciated!
