### ISSUE TITLE
Could not get file in. MSG format in file attachment

### ISSUE THREAD

**Issue by Zzxdth** [bbottema/outlook-message-parser#32]
If the attachment in the email is .msg Cannot get file  but I want .msg file
version ：1.7.4

![image](https://user-images.githubusercontent.com/28585285/83619511-8e6b7e00-a5be-11ea-94b4-1ea6f9acdcd8.png)

![image](https://user-images.githubusercontent.com/28585285/83619559-9e835d80-a5be-11ea-862a-5dabbfaa187a.png)

**Comment by bbottema** [comment]
Sorry, but I don't understand your question. Can you explain what you are trying to do and perhaps post some pseudo code of what you would want the library to do?

**Comment by Zzxdth** [comment]
I want to get the complete two files, but the files in .msg format cannot be obtained by io streaming

**Comment by Zzxdth** [comment]
[testgetmsgAttch.zip](https://github.com/bbottema/outlook-message-parser/files/4842221/testgetmsgAttch.zip)

**Comment by bbottema** [comment]
You mention two nested outlook messages in your post, but even when opening with Outlook itself I only see _one_:

![image](https://user-images.githubusercontent.com/2115718/87219017-2267fc80-c358-11ea-94ef-0596aa59b2bc.png)

I tested the library with your example and I don't see any issues. I've [added](https://github.com/bbottema/outlook-message-parser/commit/61335d90078bf3b20c4874d57ab09f43cdd8e098#diff-0570eda0f57ee61d133914fc0c1f0b92) a junit test so you can check for your self.
