### ISSUE TITLE
I got Chinese Mistaken Code when parsed outlookFileAttachment 

### ISSUE THREAD

**Issue by yuanbing692** [bbottema/outlook-message-parser#37]
OutlookFileAttachment outlookFileAttachment= (OutlookFileAttachment) outlookAttachment;
                byte[] data = outlookFileAttachment.getData();

**Comment by bbottema** [comment]
This report is impossible for me to investigate. No example result, no code on how to reproduce, no thrown exceptions, no sample email to test with, nothing.

Closing until I have more to go on...
