### ISSUE TITLE
Make field properties of class OutlookRecipient public or implement getter for it

### ISSUE THREAD

**Issue by t7l** [bbottema/outlook-message-parser#38]
I recently had a case where no mail addresses could be found in the address field of the class OutlookRecipient; instead I could find the address in the properties map, which is neither accessible nor has a getter.
I would suggest to implement a getter method to be able to access this field for such cases.

**Comment by bbottema** [comment]
Well, there's a method to get all keys, then there's one to get one value for a key.

- _.getPropertyCodes()_
- _.getPropertyValue(code)_
