### ISSUE TITLE
getBodyHTML() returns null for a specific msg file

### ISSUE THREAD

**Issue by pborissow** [bbottema/outlook-message-parser#39]
I have a bunch of msg files and for the most part, the OutlookMessageParser is working great! However, there is one file that is not working for some reason. The getBodyHTML() is returning null. I can open the message using Outlook and it looks fine. I am hesitant to attach the msg because it contains proprietary information but I would be more than happy to email it to you or share it with you some other way.

**Comment by bbottema** [comment]
Hmm, I would like to take a look indeed. If you're OK with it, you can email it to me. I'll treat it with discretion.

**Comment by pborissow** [comment]
Cool! Email is on it's way

**Comment by bbottema** [comment]
So I had a quick look, but I actually think there's no HTML body, only RTF.

If you look at _msg.getConvertedBodyHTML()_, it actually returns the same HTML you see in Outlook if you go to view source:

![image](https://user-images.githubusercontent.com/2115718/108193863-3659b500-7116-11eb-9af2-660871bf0f1b.png)
![image](https://user-images.githubusercontent.com/2115718/108193923-4bcedf00-7116-11eb-9ed8-8dec375b102f.png)


Now look at the HTML from getConvertedBodyHTML():

![image](https://user-images.githubusercontent.com/2115718/108194135-89cc0300-7116-11eb-8c92-349771a88328.png)

It's exactly the same.

**Comment by bbottema** [comment]
I'm closing this for now, unless you have some reason to suspect a bug after all.
