### ISSUE TITLE
getFromEmailFromHeaders cannot handle "quoted-name-with@at-sign"

### ISSUE THREAD

**Issue by basinilya** [bbottema/outlook-message-parser#43]
Even though Sender Name and Email addresse are stored in the fields `0xc1f` and `0x42` respectively, the parser extracts and overwrites this info from the transport headers `0x7d`.

If such a header contains quoted name with an @ at sign:

    From: "bogus@domain.com" <bogus@domain.com>

 it wrongly calls `setFromEmail("\"bogus@domain.com\"", true)` 

When trying to use this e-mail with `javax.mail` it fails:

    Caused by: javax.mail.internet.AddressException: Missing final '@domain' in string ``"bogus@domain.com"''
    	at javax.mail.internet.InternetAddress.checkAddress(InternetAddress.java:1279)

Please consider reusing or copying `new javax.mail.internet.InternetHeaders(InputStream)` for splitting the headers and `new javax.mail.internet.InternetAddress(String)` for parsing the address string.

**Comment by bbottema** [comment]
It seems you have a better grasp of the internal Outlook model than I have. Would you be interested in providing pull requests? I would be happy to integrate any improvements you might have.

**Comment by basinilya** [comment]
Give me some time. Meanwhile I figured out it's not easy to construct a test .msg file for reproduction. The bug is only visible when 7d HEADERS is the last property seen. However, poi traverses the properties binary tree in a way that does not maintain the index order.

**Comment by basinilya** [comment]
Attached the test file. (deleted property 65 with FlexHex, I hope it doesn't corrupt the message too much)
[Test at sign in personal From header.msg.zip](https://github.com/bbottema/outlook-message-parser/files/6720227/Test.at.sign.in.personal.From.header.msg.zip)
`getFromEmail()` is expected to return `"bogus@domain.com"`, but it actually returns `"\"bogus@acme.com\""`

**Comment by bbottema** [comment]
Fix released in 1.7.10
