### ISSUE TITLE
Missing object OutlookMessageAssert

### ISSUE THREAD

**Issue by gasparez15** [bbottema/outlook-message-parser#5]
I downloded the sources from repository but it appears that a class is missing:
org.simplejavamail.outlookmessageparser.model.OutlookMessageAssert

So the tests in HighoverEmailsTest cannot be executed 
This same class is missing in release 1.1.17
![screenhunter 350](https://user-images.githubusercontent.com/28052369/49215784-dc039b00-f3c9-11e8-8fd4-3c5f7d605344.png)

**Comment by bbottema** [comment]
It is generated as part of mvn test (compile test sources). Once you have run that once, the class will also be available in your IDE.

**Comment by gasparez15** [comment]
Ah, ok, thanks Benny,
I did not know that plugin :-)
Sorry for the trouble
