### ISSUE TITLE
[Question] Difference between Image attached on the email body and signature image

### ISSUE THREAD

**Issue by weslei-dias-vakt** [bbottema/outlook-message-parser#82]
Is there a way to differentiate an image attached on the email body from the signature image?

**Comment by programmiererei** [comment]
I use msg.fetchTrueAttachments for this task.

**Comment by bbottema** [comment]
What do you mean by signature image?

**Comment by weslei-dias-vakt** [comment]
@bbottema its the email signature.
i.e.

<img width="582" alt="image" src="https://github.com/user-attachments/assets/26a5ea53-eee2-4db6-9145-f7744ae8e092">

In this case if I include another inline image I will have 2.
My question Was if there is a way out of the box that the lib provide

**Comment by bbottema** [comment]
Ahh, I see. From an email structural point of view there is no difference between the images; it's all content on the same level. However the images are referenced from different places in the HTML body content, of which Simple Java Mail (and underlying mailing framework) has no knowledge about.

The only way to find out is by inspecting the HTML content yourself. There are many ways and libraries that can parse HTML so you can query it using CSS or XPath, but perhaps the easiest way is to simply look for the last <image ...> element in the text using regex and reading the content ID, which would match with an embedded image object.

That's all I can do for you. Good luck!
